name: hyper_ui_test_test
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.19.0
  google_fonts: ^6.1.0
  material_design_icons_flutter: ^7.0.7296
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  uuid: ^4.0.0
  url_launcher: ^6.1.6
  blur: ^3.1.0
  flutter_svg: ^2.0.5
  path_provider: ^2.0.11
  flutter_animate: ^4.1.1+1
  dio: ^5.0.1
  flutter_map: ^6.1.0
  geolocator: ^11.0.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  permission_handler: ^11.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/icon/
